---
name: Publish
on:
  release:
    types:
    - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm install
      - name: Publish
        run: vsce publish --no-yarn ${GITHUB_REF#refs/tags/}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
